baseURL = 'https://example.com/'
languageCode = 'ja'
title = 'tegaru-press sample site'

[module]
  [[module.imports]]
    path = 'github.com/adityatelange/hugo-PaperMod'

[params]
  defaultTheme = 'auto'
  
  homeInfoParams.Title = "Sample site"
  homeInfoParams.Content = "This is sample site"

[menu]
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/posts/'
    weight = 10